// 장미셸 바스키아 SEOUL 전시 — 소개서 11~14p 기준
export const project = {
  eyebrow: 'PORTFOLIO · EXHIBITION',
  title: '장미셸 바스키아 <br />SEOUL 전시',
  meta: [
    ['클라이언트', '숨프로젝트'],
    ['장소', '동대문디자인플라자 (DDP)'],
    ['과제', '세계적 아티스트 바스키아의 서울 전시 · 시공·미디어아트·아트샵 디자인 등 종합 수행'],
    ['수행 범위', '전시 시공 · 미디어아트 · 외부 그래픽 · 아트샵 기획·3D 제작'],
  ],
  tech: '<b>preVue</b>로 전시 동선과 작품 배치를 3D로 시뮬레이션하고, 미디어아트 콘텐츠를 자체 제작해 전시 경험을 강화했습니다.',
};

// pos: 카메라 위치, target: 바라보는 점, anchor: 3D 핀 위치 (단위 m)
// sim/real: public/images/basquiat/ 안의 이미지 이름
export const views = [
  {
    id: 'overview',
    label: '전체 조감',
    pos: [40, 44, 48],
    target: [0, 0, 0],
    fov: 42,
    orbit: true,
  },
  {
    id: 'entrance',
    label: '전시 입구',
    pos: [29, 1.7, -6],
    target: [19.6, 2.1, -6],
    fov: 58,
    orbit: false,
    anchor: [20.6, 5, -5],
    sim: 'sim-entrance',
    real: 'real-poster',
    desc: 'B2 로비에서 입구 파사드를 마주하는 시점. 기울어진 타이틀 판과 리지 힘멜 사진 판, 입구 너머 초상 벽이 한눈에 들어옵니다.',
  },
  {
    id: 'intro',
    label: '서문 · Studio of the Street',
    pos: [17.2, 1.6, -6.1],
    target: [12.2, 1.7, -6.6],
    fov: 62,
    orbit: false,
    anchor: [12.2, 4, -6.6],
    real: 'real-intro',
    desc: '입구를 지나 정면으로 만나는 초상 벽(높이 3.5m). 빨간 카펫, 베이지 벽, 벽에 끼운 양면 창문 작품의 위치를 확인합니다.',
  },
  {
    id: 'studio',
    label: '빨간 카펫 스튜디오',
    pos: [11.4, 1.6, -4],
    target: [5.6, 1.6, -8.4],
    fov: 64,
    orbit: false,
    anchor: [5.6, 4, -6.5],
    desc: 'Car Crash 와 Symphony No.1 이 걸린 빨간 카펫 방. 가벽 3.0m 위로 홀 천장이 열려 있는 구성입니다.',
  },
  {
    id: 'gallery',
    label: '회색 방 · Phooey',
    pos: [11.2, 1.6, -11.2],
    target: [2.6, 1.6, -15.4],
    fov: 64,
    orbit: false,
    anchor: [6.8, 4, -15.6],
    real: 'real-gallery',
    desc: '냉장고·화병 좌대가 있는 회색 방. 검은 자립 가벽을 돌아 Phooey 복도로 이어지고, 그 끝에 빨간 방이 보입니다.',
  },
  {
    id: 'phooey',
    label: 'Phooey & Fun Gallery',
    pos: [1.2, 1.6, -12.3],
    target: [-11.8, 1.7, -11.4],
    fov: 62,
    orbit: false,
    anchor: [-6, 4, -10.2],
    desc: '왼쪽은 네이비 벽과 낮은 단 위의 Phooey(3.55m), 오른쪽은 Fun Gallery 흑백 사진 벽. 복도 끝 네이비 감실에 Warrior 와 최영 장군이 걸립니다.',
  },
  {
    id: 'red',
    label: 'Warriors & Power Figures',
    pos: [-13, 1.6, -11.8],
    target: [-18.8, 1.7, -7],
    fov: 64,
    orbit: false,
    anchor: [-19, 4, -8.8],
    desc: '버건디 벽의 빨간 방. A-One 과 잉크 드로잉 일곱 점, 무신도 8폭 병풍 벽장이 놓입니다.',
  },
  {
    id: 'words',
    label: 'Words and Signs',
    pos: [-2.4, 1.6, 1.8],
    target: [11.4, 1.65, -1.8],
    fov: 60,
    orbit: false,
    anchor: [4, 4, -2.6],
    desc: '15m 길이의 긴 복도. 회색 벽면을 따라 작품이 이어지고 끝에서 Museum Security 의 어두운 방으로 넘어갑니다.',
  },
  {
    id: 'temple',
    label: 'Temple of Words',
    pos: [16.8, 1.6, 5.6],
    target: [8.4, 1.7, 11.6],
    fov: 66,
    orbit: false,
    anchor: [12.5, 5, 8.7],
    desc: '검은 커튼을 지나 들어서는 검은 방(밝은 바닥). 노트 페이지 격자 약 150점이 세 모서리를 돌고, 가운데 4.4m 검은 볼륨과 긴 탁자 진열장이 놓입니다.',
  },
  {
    id: 'corridor',
    label: "It's All Drawing",
    pos: [7, 1.6, 11.8],
    target: [-2.2, 1.9, 9],
    fov: 62,
    orbit: false,
    anchor: [2.4, 4.4, 8.6],
    desc: '낮은 흰 연석 위 반구대 암각화 탁본(8.3m × 3.9m)과 맞은편 드로잉 한 줄. 이 벽만 4.6m 로 높습니다.',
  },
  {
    id: 'anatomy',
    label: 'Anatomy · Hidden Signs',
    pos: [-3.4, 1.6, 7.2],
    target: [-9, 1.9, 11.4],
    fov: 62,
    orbit: false,
    anchor: [-9.4, 4.4, 9.8],
    real: 'real-corridor',
    desc: '검은 벽 앞 낮고 긴 흰 단 위의 Flesh and Spirit(3.68m). 맞은편은 인터뷰 영상, 검은 뒷벽의 구멍으로 Hidden Signs 방이 이어집니다.',
  },
  {
    id: 'media',
    label: 'Basquiat in Asia',
    pos: [1.4, 1.6, 15.6],
    target: [-4.4, 1.6, 13.6],
    fov: 62,
    orbit: false,
    anchor: [-4.8, 3.6, 14.6],
    real: 'real-media',
    desc: '빨간 카펫이 다시 시작되는 방. 프로젝션 벽과 추사 현판의 관계, 관람 거리와 화면 크기를 가늠합니다.',
  },
  {
    id: 'epilogue',
    label: '에필로그 · EXU',
    pos: [10, 1.6, 17.2],
    target: [2.6, 1.55, 13.2],
    fov: 60,
    orbit: false,
    anchor: [2.2, 3.6, 15.2],
    desc: '빨간 카펫 끝 EXU 와 그 왼쪽 검은 주름 출구 커튼. 전시 동선의 마지막 장면입니다.',
  },
  {
    id: 'shop',
    label: '아트샵',
    pos: [-5, 1.65, 18.6],
    target: [10, 1.4, 20.8],
    fov: 60,
    orbit: false,
    anchor: [3, 3.6, 20.5],
    sim: 'sim-shop',
    desc: '디자인둘레길 아트샵. 버건디 하단 띠의 굿즈 벽, 카운터, 사진 기둥의 배치와 동선 폭을 확인합니다.',
  },
];
