// 장미셸 바스키아 SEOUL 전시 — 소개서 11~14p 기준
export const project = {
  eyebrow: 'PORTFOLIO · EXHIBITION',
  title: '장미셸 바스키아 <br />SEOUL 전시',
  meta: [
    ['클라이언트', '숨프로젝트'],
    ['장소', '동대문디자인플라자 (DDP)'],
    ['과제', '세계적 아티스트 바스키아의 서울 전시 · 시공·미디어아트·아트샵 디자인 등 종합 수행'],
    ['수행 범위', '전시 시공 · 미디어아트 · 외부 그래픽 · 아트샵 기획·3D 제작'],
  ],
  tech: '<b>preVue</b>로 전시 동선과 작품 배치를 3D로 시뮬레이션하고, 미디어아트 콘텐츠를 자체 제작해 전시 경험을 강화했습니다.',
};

// pos: 카메라 위치, target: 바라보는 점, anchor: 3D 핀 위치 (단위 m)
// sim/real: public/images/basquiat/ 안의 이미지 이름
export const views = [
  {
    id: 'overview',
    label: '전체 조감',
    pos: [40, 44, 48],
    target: [0, 0, 0],
    fov: 42,
    orbit: true,
  },
  {
    id: 'entrance',
    label: '전시 입구',
    pos: [29, 1.7, -3.2],
    target: [20, 2.1, -3.4],
    fov: 58,
    orbit: false,
    anchor: [21, 5, -2.7],
    sim: 'sim-entrance',
    real: 'real-poster',
    desc: 'B2 로비에서 입구 파사드를 마주하는 시점. 기울어진 타이틀 판과 리지 힘멜 사진 판, 입구 너머 초상 벽이 한눈에 들어옵니다.',
  },
  {
    id: 'intro',
    label: '서문 · Studio of the Street',
    pos: [19, 1.7, -3.2],
    target: [12, 1.8, -5],
    fov: 64,
    orbit: false,
    anchor: [12.2, 4.3, -5],
    real: 'real-intro',
    desc: '입구를 지나 정면으로 만나는 초상 벽. 빨간 카펫, 베이지 벽, 벽에 끼운 양면 창문 작품의 위치를 확인합니다.',
  },
  {
    id: 'gallery',
    label: '스튜디오 · Phooey',
    pos: [15.8, 1.65, -13.2],
    target: [4, 1.8, -15.6],
    fov: 62,
    orbit: false,
    anchor: [10.6, 4, -14.6],
    real: 'real-gallery',
    desc: '냉장고·화병 좌대가 있는 회색 방에서 네이비 벽의 Phooey 복도와 그 끝의 빨간 방을 바라보는 시점입니다.',
  },
  {
    id: 'temple',
    label: 'Temple of Words',
    pos: [0.5, 1.7, -2.6],
    target: [-6, 1.6, -2.6],
    fov: 66,
    orbit: false,
    anchor: [-3.4, 5.2, -2.6],
    desc: '검은 커튼을 지나 들어서는 네이비 방. 노트 페이지 격자와 가운데 검은 상자, 받침 진열장의 배치를 봅니다.',
  },
  {
    id: 'corridor',
    label: "It's All Drawing",
    pos: [1.6, 1.65, 3],
    target: [18.5, 1.8, 2.9],
    fov: 60,
    orbit: false,
    anchor: [6.5, 5, 1.6],
    desc: '낮은 흰 선반 위 반구대 암각화 탁본(8.3m)과 맞은편 드로잉, 복도 끝 영상 프로젝션까지의 시선을 확인합니다.',
  },
  {
    id: 'anatomy',
    label: 'Anatomy',
    pos: [12.3, 1.65, 7.4],
    target: [5, 1.8, 8.2],
    fov: 62,
    orbit: false,
    anchor: [8.2, 5, 10.8],
    real: 'real-corridor',
    desc: '검은 벽 앞 흰 낮은 좌대 위 Flesh and Spirit(3.68m), 맞은편 세 작품, 방 끝 인터뷰 영상까지의 시선입니다.',
  },
  {
    id: 'media',
    label: '미디어아트',
    pos: [8.2, 1.65, 13.5],
    target: [12.3, 1.7, 13.5],
    fov: 64,
    orbit: false,
    anchor: [12.2, 4, 13.5],
    real: 'real-media',
    desc: 'Basquiat in Asia 의 프로젝션 벽. 관람 거리와 화면 크기, 추사 현판과의 관계를 가늠합니다.',
  },
  {
    id: 'epilogue',
    label: '에필로그 · EXU',
    pos: [12.2, 1.65, 13.4],
    target: [0, 1.5, 13],
    fov: 64,
    orbit: false,
    anchor: [0.2, 4, 12.7],
    desc: '빨간 카펫 끝 네이비 벽의 EXU 와 왼쪽 검은 출구 커튼. 전시 동선의 마지막 장면입니다.',
  },
  {
    id: 'shop',
    label: '아트샵',
    pos: [-5, 1.65, 18.6],
    target: [10, 1.4, 20.8],
    fov: 60,
    orbit: false,
    anchor: [3, 3.6, 20.5],
    sim: 'sim-shop',
    desc: '디자인둘레길 아트샵. 버건디 하단 띠의 굿즈 벽, 카운터, 사진 기둥의 배치와 동선 폭을 확인합니다.',
  },
];
