// LOCAL POWER 2025 홍콩 패션 in 서울 — 소개서 19~22p 기준
export const project = {
  eyebrow: 'PORTFOLIO · 2025',
  title: 'LOCAL POWER 2025 <br />홍콩 패션 in 서울',
  meta: [
    ['클라이언트', '중화인민공화국 홍콩 특별행정구 (홍콩 정부)'],
    ['장소', '성수동 세원정밀 창고'],
    ['과제', '홍콩 정부 주최 패션쇼·전시를 서울에서 개최 · 패션쇼+전시+네트워킹 공간 통합 구성'],
    ['수행 범위', '패션쇼·전시 기획 · 시공 · 제작 · 운영 일체'],
  ],
  tech: '<b>preVue</b>로 패션쇼 무대·전시·네트워킹 공간을 3D로 사전 시뮬레이션하고, 시뮬레이션을 기반으로 공간 효율을 최적화했습니다.',
};

// pos: 카메라 위치, target: 바라보는 점, anchor: 3D 핀 위치 (단위 m), phase: 'show' 면 쇼 당일(9.27) 구성으로 전환
// 좌표: 창고 중심 원점. +x 성수이로18길(박공 가림막), -z 서쪽 입구 마당, -x 뮤직 월·런웨이 LED 쪽
export const views = [
  {
    id: 'overview',
    label: '전체 조감',
    pos: [58, 44, 44],
    target: [4, 0, -4],
    fov: 42,
    orbit: true,
  },
  {
    id: 'entrance',
    label: '거리·입구 조감',
    pos: [50, 34, 8],
    target: [2, 0, -5],
    fov: 38,
    orbit: true,
    anchor: [17.2, 4.6, 0],
    sim: 'sim-aerial',
    desc: '성수이로18길에서 본 창고 박공면의 선버스트 가림막과 서쪽 입구 마당, 길 건너 S-Factory 까지의 거리 맥락입니다.',
  },
  {
    id: 'street',
    label: '성수이로18길',
    pos: [29.5, 1.7, 9],
    target: [14, 3, -6],
    fov: 62,
    orbit: false,
    anchor: [17.2, 3.8, -2],
    desc: '길 건너 가로수 아래에서 본 흰 벽돌 박공과 11.8m 가림막, 블록 담의 번지판 20, 초록 철문.',
  },
  {
    id: 'yard',
    label: '입구 마당',
    pos: [16.3, 1.65, -10.5],
    target: [-5, 1.6, -11.5],
    fov: 66,
    orbit: false,
    anchor: [8, 3.4, -7.4],
    real: 'real-entrance',
    desc: '초록 철문을 지나 본 마당. 왼쪽 3m 주황 가림막과 빨간 길, 끝의 홍콩 간판 포토월, 오른쪽 포토 소품과 체험 존입니다.',
  },
  {
    id: 'photowall',
    label: '홍콩 간판 포토월',
    pos: [2.5, 1.6, -11],
    target: [-5.2, 1.6, -11.3],
    fov: 58,
    orbit: false,
    anchor: [-5.2, 3.6, -11.3],
    real: 'real-photowall',
    desc: '마당 끝 포토월. 홍콩 거리 간판을 모으고 위에 후원사 띠를 얹었습니다.',
  },
  {
    id: 'exhibit',
    label: '전시 입구 쪽',
    pos: [14.3, 1.6, -1.2],
    target: [0, 1.5, 1.5],
    fov: 64,
    orbit: false,
    anchor: [10.5, 4.2, 0.6],
    real: 'real-exhibit',
    desc: '실 커튼 원기둥 섬과 URBAN JUNGLE 니트 벽, 스카이라인 벽을 입구 쪽에서 본 시점입니다.',
  },
  {
    id: 'curtain',
    label: '물결 커튼 섬',
    pos: [-4, 1.6, -2.6],
    target: [-4, 1.5, 3.2],
    fov: 64,
    orbit: false,
    anchor: [-4, 4.2, 2.7],
    real: 'real-curtain',
    desc: 'S자 좌대 위 흰 보일 커튼과 RUNWAY TO TOMORROW 10벌. 앞뒤로 다섯 벌씩 섭니다.',
  },
  {
    id: 'music',
    label: '뮤직 월',
    pos: [-8, 1.6, -0.5],
    target: [-16.3, 1.8, 1],
    fov: 64,
    orbit: false,
    anchor: [-16.2, 4.2, 1.5],
    desc: '창고 안쪽 끝 가벽의 거울·비닐 원판과 CD, 흰 큐브 위 다섯 벌.',
  },
  {
    id: 'runway',
    label: '쇼 당일 · 런웨이',
    phase: 'show',
    pos: [6.5, 1.8, 0],
    target: [-16, 2, 0],
    fov: 58,
    orbit: false,
    anchor: [4.7, 1.4, 0],
    sim: 'sim-runway',
    real: 'real-runway',
    desc: '9월 27일 쇼 당일 구성. 20 × 3m 런웨이와 양쪽 흰 박스 벤치 3열, 끝의 LED 세 면을 봅니다.',
  },
  {
    id: 'showtop',
    label: '쇼 당일 · 전경',
    phase: 'show',
    pos: [5.5, 3.4, -3],
    target: [-12, 0.3, 0.5],
    fov: 66,
    orbit: true,
    anchor: [-5.3, 3.6, 0],
    sim: 'sim-showtop',
    desc: '쇼 당일 창고 전체. 흰 조명탑 여덟 개에 무빙 라이트가 네 개씩 달렸습니다.',
  },
];
