// 현대자동차 1억대 생산기념 전시 — 소개서 7~10p 기준
export const project = {
  eyebrow: 'PORTFOLIO · EXHIBITION',
  title: '현대자동차 <br />1억대 생산기념 전시',
  meta: [
    ['클라이언트', '현대자동차'],
    ['장소', '현대 모터스튜디오 도산'],
    ['과제', '글로벌 누적 1억대 생산을 기념하는 전시 공간 구현 · 브랜드 헤리티지와 미래 비전을 동시에 전달'],
    ['수행 범위', '공간 기획 · 3D 시뮬레이션 · 전시 시공'],
  ],
  tech: '<b>preVue</b>로 실측 공간과 전시 오브제를 3D 모델링하고, 시뮬레이션 단계에서 레이아웃·조명·동선을 확정해 현장 수정을 최소화했습니다.',
};

// 좌표: 기준층 윤곽 중심 원점, 1F 바닥 = 0. -z 도산대로(북, 입구), 45° 모따기 유리면 = 도산사거리(서북서), -x 언주로
// 층: 1F 0 · 2F(메자닌) 3.75 · 3F 7.65 · 4F 12.63 · 5F 17.61 · 지붕 27.57 (건축물대장·서아키텍스 도면)
export const views = [
  {
    id: 'overview',
    label: '전체 조감',
    pos: [-42, 34, -40],
    target: [1, 8, 1],
    fov: 40,
    orbit: true,
  },
  {
    id: 'facade',
    label: '도산사거리 외관',
    pos: [-31, 1.7, -25],
    target: [-3, 11, -3],
    fov: 58,
    orbit: false,
    anchor: [-6.8, 20, -7.2],
    real: 'real-facade',
    desc: '도산사거리에서 본 모따기 유리면. 3~5층 로테이터 자리마다 노란 걸이에 매단 차 그림 패널이 거리를 향합니다.',
  },
  {
    id: 'lobby',
    label: '1F 첫걸음',
    pos: [5, 1.45, -9.3],
    target: [-4.3, 1.1, -3.6],
    fov: 72,
    orbit: false,
    anchor: [-4.3, 4, -3.2],
    sim: 'sim-ground',
    real: 'real-pony',
    desc: '북쪽 전실에서 본 1층. 코티나 Mk2와 포니 에콰도르 택시, 경 100,000,001대 생산 축 아치, 모따기 안쪽 대형 스크린의 관계를 봅니다.',
  },
  {
    id: 'conveyor',
    label: '천장 컨베이어',
    pos: [3, 5.25, -7],
    target: [-6.4, 5.4, -6.4],
    fov: 76,
    orbit: false,
    anchor: [-4.5, 7.2, -4.5],
    sim: 'sim-atrium',
    real: 'real-conveyor',
    desc: '2층 카페 쪽에서 본 보이드. 노란 걸이 24개에 매달린 1:4 차체가 도는 레일이 계단 쪽에서 눈높이로 내려옵니다.',
  },
  {
    id: 'darkroom',
    label: '2F 1억 대의 궤적',
    pos: [-6, 5.35, 5],
    target: [-6.6, 4.65, 12.8],
    fov: 76,
    orbit: false,
    anchor: [-6.6, 7.4, 8.9],
    real: 'real-archive',
    desc: '어두운 방의 벽 전시 세 개(첫걸음·도약의 발걸음·다시, 첫걸음)와 디오라마, 가운데 C자 사진 테이블.',
  },
  {
    id: 'gallery3',
    label: '3F 원동력',
    pos: [-6.2, 9, 2.6],
    target: [3, 8.65, -6],
    fov: 72,
    orbit: false,
    anchor: [-2.6, 11.6, -0.9],
    real: 'real-elantra',
    desc: '쏘나타 Y1·스쿠프·엘란트라가 둥근 조명 박스 아래 서 있는 3층. 알파 엔진과 아카이브 테이블, 파란 리본 벽이 함께 보입니다.',
  },
  {
    id: 'drafting',
    label: '1980년대 설계실',
    pos: [-5.6, 9.25, 6.6],
    target: [-5.6, 8.85, 13],
    fov: 72,
    orbit: false,
    anchor: [-5.6, 11, 10.6],
    sim: 'sim-drafting',
    desc: '크림색 벽과 제도판·책상·도면 라이트박스로 재현한 1980년대 설계실.',
  },
  {
    id: 'suv',
    label: '4F SUV',
    pos: [2, 14.03, 1.7],
    target: [-4, 13.63, -5.5],
    fov: 74,
    orbit: false,
    anchor: [-1.9, 16.6, -2.2],
    desc: '파란 바닥과 배경 위 싼타페·코나 일렉트릭·캐스퍼 일렉트릭, 유리 쪽 로테이터의 세워진 하부 셸.',
  },
  {
    id: 'ev',
    label: '5F EV',
    pos: [1.6, 18.91, 1.4],
    target: [-4, 18.81, -5],
    fov: 74,
    orbit: false,
    anchor: [-1.9, 21.6, -2.2],
    desc: '아이오닉 5·아이오닉 5 N 라인·아이오닉 6 과 충전기, E-GMP 하부 로테이터.',
  },
];
