// 현대자동차 1억대 생산기념 전시 — 소개서 7~10p 기준
export const project = {
  eyebrow: 'PORTFOLIO · EXHIBITION',
  title: '현대자동차 <br />1억대 생산기념 전시',
  meta: [
    ['클라이언트', '현대자동차'],
    ['장소', '현대 모터스튜디오 도산'],
    ['과제', '글로벌 누적 1억대 생산을 기념하는 전시 공간 구현 · 브랜드 헤리티지와 미래 비전을 동시에 전달'],
    ['수행 범위', '공간 기획 · 3D 시뮬레이션 · 전시 시공'],
  ],
  tech: '<b>preVue</b>로 실측 공간과 전시 오브제를 3D 모델링하고, 시뮬레이션 단계에서 레이아웃·조명·동선을 확정해 현장 수정을 최소화했습니다.',
};

// 좌표: 건물 중심이 원점. -x: 미디어월(벽화) 쪽 유리벽, +z: 정면 유리 파사드
// 층 높이: 1F 0m · 2F 6m · 3F 11.5m · 지붕 16.8m
export const views = [
  {
    id: 'overview',
    label: '전체 조감',
    pos: [42, 34, 44],
    target: [-1, 6, -1],
    fov: 42,
    orbit: true,
  },
  {
    id: 'atrium',
    label: '상층 난간',
    pos: [5.2, 7.7, 12.4],
    target: [-12, 7.5, -3],
    fov: 62,
    orbit: false,
    anchor: [5, 8.2, 11.5],
    sim: 'sim-atrium',
    desc: '2층 난간에서 아트리움을 내려다보는 시점. 컨베이어 레일과 미디어월, 1층 차량이 한 화면에 어떻게 겹쳐 보이는지 확인합니다.',
  },
  {
    id: 'conveyor',
    label: '레일 아래',
    pos: [-5, 1.6, 9],
    target: [-9, 13.5, -1],
    fov: 64,
    orbit: false,
    anchor: [-9, 11.2, 1.5],
    real: 'real-conveyor',
    desc: '천장 레일에 매달린 차체 크래들을 올려다보는 시점. 레일 궤적과 행잉 높이, 크래들 간격을 검토합니다.',
  },
  {
    id: 'lobby',
    label: '1층 전시',
    pos: [0.5, 1.65, 13],
    target: [-12, 3.2, 2],
    fov: 58,
    orbit: false,
    anchor: [-6, 5.8, 8.5],
    sim: 'sim-ground',
    real: 'real-pony',
    desc: '1층 관람객 눈높이 시점. 클래식카와 아치 조형물, 미디어월이 입구 동선에서 어떻게 보이는지 미리 봅니다.',
  },
  {
    id: 'gate',
    label: '1억대 게이트',
    pos: [12.2, 13.3, 7.2],
    target: [14, 12.9, -6],
    fov: 55,
    orbit: true,
    anchor: [14, 16.2, -4.6],
    sim: 'sim-gate',
    desc: '게이트 조형물 정면 시점. 좌우 영상 패널과 전시 차량, 중앙 오브제의 배치와 조명을 확인합니다.',
  },
  {
    id: 'heritage',
    label: '헤리티지 존',
    pos: [12.6, 13.2, 12.6],
    target: [17.5, 12.2, 6.5],
    fov: 58,
    orbit: false,
    anchor: [15.5, 14.6, 8],
    sim: 'sim-drafting',
    real: 'real-elantra',
    desc: '역대 차량과 아카이브 패널이 놓인 헤리티지 구역. 곡면 파티션과 조명, 관람 거리를 점검합니다.',
  },
];
