// APEC CEO Summit 특별만찬 — 소개서 15~18p 기준
export const project = {
  eyebrow: 'PORTFOLIO · 2025',
  title: 'APEC CEO Summit <br />특별만찬',
  meta: [
    ['클라이언트', '대한상공회의소 · 주식회사 스피언스'],
    ['장소', '경주 황룡원'],
    ['과제', '국제 정상급 행사의 레이아웃·시스템·운영 전 과정. 보안과 품질의 최고 수준 요구'],
    ['수행 범위', '레이아웃 기획 · 3D 시뮬레이션 · 시스템 설치·운영 · 콘텐츠 제작 · 행사 운영'],
  ],
  tech: '<b>preVue</b>로 행사장 전체를 3D로 구현해 동선·좌석·무대 배치를 사전 검증하고, 시스템 설치와 기술 운영까지 수행했습니다.',
};

// pos: 카메라 위치, target: 바라보는 점, anchor: 3D 핀 위치 (단위 m)
// orbit: true면 대상 주위를 회전, false면 제자리에서 둘러보기(1인칭)
// sim/real: public/images/apec/ 안의 이미지 이름
export const views = [
  {
    id: 'overview',
    label: '전체 조감',
    pos: [-40, 64, 92],
    target: [6, 6, -8],
    fov: 42,
    orbit: true,
  },
  {
    id: 'drone',
    label: '드론뷰',
    pos: [34, 40, 30],
    target: [-4, 0, -12],
    fov: 45,
    orbit: true,
    anchor: [28, 32, 24],
    sim: 'sim-front',
    real: 'real-drone',
    desc: '원형 테이블, 히터, 석재 동선의 배치를 상공에서 한눈에 확인하는 시점입니다.',
  },
  {
    id: 'terrace',
    label: '귀빈동 테라스',
    pos: [26.5, 14.6, 20.1],
    target: [-10.1, 23.4, -26.5],
    fov: 84,
    orbit: false,
    anchor: [25.5, 14.2, 19.4],
    sim: 'sim-aerial',
    real: 'real-terrace',
    desc: '연수동 북동동 옥상 테라스. 중도타워와 무대, 잔디 위 만찬장이 한 화면에 담기는 구도로 조명과 LED 연출을 맞춰봅니다.',
  },
  {
    id: 'stage',
    label: '무대 위',
    pos: [6, 3.1, -15.4],
    target: [3, 1.2, 12],
    fov: 62,
    orbit: false,
    anchor: [6, 3.6, -14.6],
    real: 'real-show',
    desc: '연사가 서는 포디움 시점. 객석 전체가 시야에 들어오는지 확인합니다.',
  },
  {
    id: 'vip',
    label: '관객석',
    pos: [-2.2, 1.45, -0.9],
    target: [6, 4.2, -19],
    fov: 56,
    orbit: false,
    anchor: [-3, 2.4, -3],
    sim: 'sim-table',
    real: 'real-table',
    desc: '앞줄 테이블에 앉았을 때 무대와 LED 스크린이 어떻게 보이는지 미리 봅니다.',
  },
  {
    id: 'foh',
    label: '콘솔 부스',
    pos: [15.2, 3.9, -41.8],
    target: [5, 0.4, -24],
    fov: 66,
    orbit: false,
    anchor: [11, 3.4, -37.6],
    sim: 'sim-ground',
    real: 'real-foh',
    desc: '무대 뒤 신평루 아래층에 차린 콘솔 부스. 물탱크와 대기 천막 너머로 무대를 보며 조명·음향·영상을 운영했습니다.',
  },
];
